# Generated by Django 4.2.7 on 2023-11-22 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_blog_content'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
