# Generated by Django 4.2.7 on 2023-11-27 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.CharField(default='A long time ago, In a galaxy far far away...', max_length=100),
        ),
    ]
